### ISSUE TITLE
Add documentation on contributing guidelines

### ISSUE THREAD

**Issue by IMS94** [chr24x7/chr247.com#10]
Right now we have not enough documentation to help the contributors and users. A nice Documentation for contribution would be a great help for the project.

**Comment by Dinika** [comment]
Would like to claim to this issue. Is knowledge in PHP mandatory?

**Comment by IMS94** [comment]
@Dinika No need to have any PHP knowledge at all. You can find enough templates for contributing guidelines online. [This](https://github.com/Z-Editor/Z-Editor/blob/master/CONTRIBUTING.md) is one such example.

**Comment by inidaname** [comment]
@Dinika I will open a PR 
I can send you some I am using link to source is also in the document

**Comment by Dinika** [comment]
@inidaname I'm sorry I didn't quite understand you.
Have you already solved this issue? 
Or is there some link in a file that you think will be helpful to get started on solving this issue. 
If it's the latter, thanks, I'd like to check that link.

**Comment by inidaname** [comment]
@Dinika I sent in a Contribution Template I use myself hoping it will solve this issue and the link in the file is the authors of the template

**Comment by IMS94** [comment]
@inidaname I commented on your PR. Unfortunately that contributing guideline was not what I was looking for, I had given an example [contributing.md](https://github.com/Z-Editor/Z-Editor/blob/master/CONTRIBUTING.md) in the description. Can you look at that and make a update the PR with a similar one?

@Dinika You are also welcome to put a PR. Please refer the example I have given and try to make it look like that.

**Comment by Dinika** [comment]
@IMS94 I've opened a PR for this issue.

**Comment by IMS94** [comment]
@Dinika I have merged it. Thanks for the PR.

@inidaname Thanks for your PR too. But unfortunately, that wasn't what I was looking for. Keep on contributing!
