### ISSUE TITLE
Integrate travis CI for phpunit tests

### ISSUE THREAD

**Issue by IMS94** [chr24x7/chr247.com#9]
Need to add Travis CI to run phpunit tests

**Comment by narendravaghela** [comment]
I can add Travis ci configuration file if you want, but you then have to authorize it with Travis.

**Comment by IMS94** [comment]
@narendravaghela Yes, I can authorize it with Travis. But you may need to look at the tests first in order to identify what are the constraints when using Travis. 

These phpunit tests require migrating and seeding to be done initially to a database. Tests refer the database tables later. Will that be possible with Travis?

**Comment by narendravaghela** [comment]
Let me check it on my fork first. We can do the database stuff with Travis, but that requires little bit time and efforts.

**Comment by IMS94** [comment]
@narendravaghela I see. Let me know what you think.

**Comment by narendravaghela** [comment]
@IMS94 
I have generated PR. You can see the output of CI on my fork here - https://travis-ci.org/narendravaghela/chr247.com
